server {
    listen 80;
    server_name _;
    charset utf-8;
    root /usr/share/nginx/html;
    autoindex on;          # 打开 http://群晖IP:8899/ 可看到文件列表, 方便验证
    location / {
        try_files $uri =404;
    }
}
